### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Shiv-95** [heikkipora/js-fractal-compression#12]
Code is not working ig

**Comment by telecran-telecrit** [comment]
> Code is not working ig

@Shiv-95! Nothing must work on nodejs, it's normal. "Version 16 and 16 iterations is enough". ;-)

**Comment by heikkipora** [comment]
This project is a toy and not maintained.

**Comment by telecran-telecrit** [comment]
@heikkipora Toy or joke?
