### ISSUE TITLE
error 800A03F6

### ISSUE THREAD

**Issue by Lbdevaa** [heikkipora/js-fractal-compression#4]
line 1 symbol 1
bin/encode.js
![Безымянный](https://user-images.githubusercontent.com/31518980/115531301-0cf00d80-a2ae-11eb-8180-9585287b1805.png)

**Comment by heikkipora** [comment]
Looks like your Windows is trying to interpret the ES6 script files as JScript or even VBScript. Those scripts in `bin` folder expect a unix-like command line environment (they are looking for /usr/bin/env to find node.js).

Would WSL from Microsoft help with that ? (I have no experience on that as a mac/linux developer..)
